import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Sidebar riêng cho Java
  javaSidebar: [{type: 'autogenerated', dirName: 'java'}],
  javaGpcoderSidebar: [{type: 'autogenerated', dirName: 'java-gpcoder'}],
  javaInterviewSidebar: [{type: 'autogenerated', dirName: 'java-interview'}],
  ieltsSidebar: [{type: 'autogenerated', dirName: 'ielts'}],
  reactSidebar: [{type: 'autogenerated', dirName: 'react'}],
  gitSidebar: [{type: 'autogenerated', dirName: 'git'}],
  javascriptSidebar: [{type: 'autogenerated', dirName: 'javascript'}],
  typescriptSidebar: [{type: 'autogenerated', dirName: 'typescript'}],
  backendSidebar: [{type: 'autogenerated', dirName: 'backend'}],
  sqlSidebar: [{type: 'autogenerated', dirName: 'sql'}],
  nextjsSidebar: [{type: 'autogenerated', dirName: 'nextjs'}],
  seoSidebar: [{type: 'autogenerated', dirName: 'seo'}],
  interviewSidebar: [{type: 'autogenerated', dirName: 'interview'}],
  nodejsSidebar: [{type: 'autogenerated', dirName: 'nodejs'}],
  dockerSidebar: [{type: 'autogenerated', dirName: 'docker'}],
  claudeSidebar: [{type: 'autogenerated', dirName: 'claude'}],
  reactNativeSidebar: [{type: 'autogenerated', dirName: 'react-native'}],
  microFrontendSidebar: [{type: 'autogenerated', dirName: 'micro-frontend'}],
  webSecuritySidebar: [{type: 'autogenerated', dirName: 'web-security'}],
};

export default sidebars;
